# Generated by Django 3.1.1 on 2020-10-05 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('ime_oca', models.CharField(max_length=50)),
                ('godina_rodjenja', models.DateField(blank=True, null=True)),
                ('mjesto_rodjenja', models.CharField(max_length=50)),
                ('mjesto_prebivalista', models.CharField(max_length=50)),
                ('adresa', models.CharField(max_length=50)),
                ('postanski_broj', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=50)),
                ('naziv_preduzeca', models.CharField(blank=True, max_length=250, null=True)),
                ('adresa_preduzeca', models.CharField(blank=True, max_length=250, null=True)),
                ('mjesto_preduzeca', models.CharField(blank=True, max_length=250, null=True)),
                ('postanski_broj_preduzeca', models.CharField(blank=True, max_length=250, null=True)),
                ('IBAN', models.CharField(blank=True, default='BA395620998146211620', max_length=250, null=True)),
                ('SWIFT_BIC', models.CharField(blank=True, default='RAZBBA22', max_length=50, null=True)),
                ('telefon_mobilni', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('zvanje', models.CharField(blank=True, max_length=150, null=True)),
                ('pozicija', models.CharField(blank=True, max_length=150, null=True)),
                ('email_preduzeca', models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='Email preduzeca')),
                ('web_stranica', models.URLField(blank=True, null=True)),
                ('banka_racun', models.CharField(blank=True, max_length=150, null=True)),
                ('profilna_slika', models.ImageField(blank=True, null=True, upload_to='slike')),
                ('drzava', models.CharField(blank=True, choices=[('Bosna i Hercegovina', 'Bosna i Hercegovina'), ('Germany', 'Germany'), ('Poland', 'Poland')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_fakture', models.CharField(default='0001', max_length=50)),
                ('drzava', models.CharField(blank=True, max_length=100, null=True)),
                ('datum_fakture', models.DateField(default=django.utils.timezone.now)),
                ('rok_placanja', models.DateField(default=django.utils.timezone.now)),
                ('placeno', models.CharField(choices=[('P', 'Placeno'), ('NP', 'Nije placeno')], default='NP', max_length=20)),
                ('racun', models.CharField(blank=True, default='RAČUN', max_length=20, null=True)),
                ('racun_njemacki', models.CharField(blank=True, default='RECHNUNG', max_length=30, null=True)),
                ('avansno_uplaceno', models.DecimalField(decimal_places=2, default=0.0, help_text='Devizno plaćanje upisati vrijednost u evrima', max_digits=10)),
                ('nacin_placanja', models.CharField(blank=True, default='Žiro račun/Gotovinsko plaćanje', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-broj_fakture'],
            },
        ),
        migrations.CreateModel(
            name='FaktureBrojevi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_fakture', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kupac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('naziv_firme', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lokacija_grad', models.CharField(max_length=50)),
                ('adresa_kupca', models.CharField(max_length=150)),
                ('postanski_broj', models.CharField(max_length=50)),
                ('drzava', models.CharField(blank=True, choices=[('Bosna i Hercegovina', 'Bosna i Hercegovina'), ('Germany', 'Germany'), ('Poland', 'Poland')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pozicija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_pozicije', models.CharField(blank=True, max_length=100, null=True)),
                ('pos_NSN', models.CharField(blank=True, max_length=30, null=True)),
                ('pos_broj', models.IntegerField(blank=True, default=0, null=True)),
                ('cijena', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('jedinica_mjere', models.CharField(default='kom', max_length=50)),
            ],
            options={
                'ordering': ['naziv_pozicije'],
            },
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_usluge', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bam_evro', models.DecimalField(decimal_places=6, default=1.95583, max_digits=8)),
                ('valute', models.CharField(choices=[('EUR', 'EUR'), ('BAM', 'BAM'), ('USD', 'USD'), ('PLN', 'PLN')], default='BAM', max_length=10)),
                ('vrijednost_valute', models.DecimalField(decimal_places=6, default=1.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Prodaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(default=0)),
                ('neto_cijena_proizvoda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pdv', models.CharField(choices=[('0', '0'), ('17', '17')], default='0', max_length=10)),
                ('bruto_cijena_proizvoda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('neto_cijena', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bruto_cijena', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('faktura', models.ForeignKey(help_text='Izaberi broj fakture', on_delete=django.db.models.deletion.CASCADE, to='fakture.faktura')),
                ('opis_usluge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fakture.usluga')),
                ('pozicija', models.ForeignKey(help_text='Izaberi uslugu', on_delete=django.db.models.deletion.CASCADE, to='fakture.pozicija')),
            ],
            options={
                'ordering': ['faktura'],
            },
        ),
        migrations.AddField(
            model_name='faktura',
            name='kupac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakture.kupac'),
        ),
        migrations.AddField(
            model_name='faktura',
            name='valuta',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='fakture.valute'),
        ),
    ]
