# Generated by Django 3.1.1 on 2020-10-06 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='valuta',
            field=models.ForeignKey(blank=True, default='BAM', on_delete=django.db.models.deletion.CASCADE, to='fakture.valute'),
        ),
        migrations.AlterField(
            model_name='valute',
            name='bam_evro',
            field=models.DecimalField(decimal_places=6, default=1.95583, help_text='Unesite trenutni odnos BAM u odnosu na stranu valutu. <br>Maksimalan broj decimalnih mjeste je šest.', max_digits=8),
        ),
    ]
