# Generated by Django 3.1.1 on 2020-10-06 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fakture', '0002_auto_20201006_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_ponude', models.CharField(default='0001', max_length=50)),
                ('drzava', models.CharField(blank=True, max_length=100, null=True)),
                ('datum_fakture', models.DateField(default=django.utils.timezone.now)),
                ('rok_placanja', models.DateField(default=django.utils.timezone.now)),
                ('placeno', models.CharField(choices=[('P', 'Placeno'), ('NP', 'Nije placeno')], default='NP', max_length=20)),
                ('racun', models.CharField(blank=True, default='RAČUN', max_length=20, null=True)),
                ('racun_njemacki', models.CharField(blank=True, default='RECHNUNG', max_length=30, null=True)),
                ('avansno_uplaceno', models.DecimalField(decimal_places=2, default=0.0, help_text='Devizno plaćanje upisati vrijednost u evrima', max_digits=10)),
                ('nacin_placanja', models.CharField(blank=True, default='Žiro račun/Gotovinsko plaćanje', max_length=100, null=True)),
                ('kupac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakture.kupac')),
                ('valuta', models.ForeignKey(blank=True, default='BAM', on_delete=django.db.models.deletion.CASCADE, to='fakture.valute')),
            ],
            options={
                'ordering': ['-broj_ponude'],
            },
        ),
        migrations.AlterField(
            model_name='prodaja',
            name='pozicija',
            field=models.ForeignKey(help_text='Izaberi poziciju', on_delete=django.db.models.deletion.CASCADE, to='fakture.pozicija'),
        ),
        migrations.CreateModel(
            name='ProdajaPonuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(default=0)),
                ('neto_cijena_proizvoda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pdv', models.CharField(choices=[('0', '0'), ('17', '17')], default='0', max_length=10)),
                ('bruto_cijena_proizvoda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('neto_cijena', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bruto_cijena', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('opis_usluge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fakture.usluga')),
                ('ponuda', models.ForeignKey(help_text='Izaberi broj ponude', on_delete=django.db.models.deletion.CASCADE, to='fakture.ponuda')),
                ('pozicija', models.ForeignKey(help_text='Izaberi poziciju', on_delete=django.db.models.deletion.CASCADE, to='fakture.pozicija')),
            ],
            options={
                'ordering': ['ponuda'],
            },
        ),
    ]
