# Generated by Django 3.1.1 on 2020-10-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakture', '0003_auto_20201006_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponuda',
            old_name='datum_fakture',
            new_name='datum_ponude',
        ),
    ]
